import { StyleSheet } from "react-native";
import type { ThemeColors } from "../../../constants/theme";

export function createTodoModalStyles(colors: ThemeColors) {
  return StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    overlayCenter: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      padding: 24,
    },
    keyboardView: { width: "100%" },
    sheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 24,
      paddingTop: 12,
      paddingBottom: 0,
    },
    modal: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 24,
      maxHeight: "90%",
    },
    scrollContent: { flex: 1 },
    scrollContentContainer: { paddingBottom: 16, flexGrow: 1 },
    actionsBar: {
      flexDirection: "row",
      gap: 12,
      justifyContent: "flex-end",
      flexWrap: "wrap",
      paddingTop: 16,
      paddingHorizontal: 0,
      marginTop: 8,
    },
    handle: {
      width: 40,
      height: 4,
      backgroundColor: colors.border,
      borderRadius: 2,
      alignSelf: "center",
      marginBottom: 20,
    },
    stepIndicator: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 8,
      marginBottom: 8,
    },
    stepDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.border,
    },
    stepDotActive: { backgroundColor: colors.accent, width: 24 },
    stepDotDone: { backgroundColor: colors.accent },
    stepLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.textMuted,
      marginBottom: 20,
      textAlign: "center",
    },
    stepContent: { gap: 16 },
    title: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 20,
    },
    section: { marginBottom: 20 },
    label: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.textMuted,
      marginBottom: 8,
    },
    typeHint: { fontSize: 14, color: colors.textMuted, marginBottom: 16 },
    typeGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
      marginBottom: 24,
    },
    typeCard: {
      flex: 1,
      minWidth: "42%",
      maxWidth: "48%",
      alignItems: "center",
      padding: 14,
      borderRadius: 16,
      backgroundColor: colors.surfaceHover,
    },
    typeCardActive: {
      borderWidth: 1,
      borderColor: colors.accent,
      backgroundColor: colors.accentDim,
    },
    typeCardText: {
      fontSize: 13,
      fontWeight: "500",
      color: colors.textMuted,
      marginTop: 8,
      textAlign: "center",
      flexShrink: 1,
    },
    typeCardTextActive: { color: colors.accent },
    typeRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    typeChip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 24,
      backgroundColor: colors.surfaceHover,
    },
    typeChipActive: {
      backgroundColor: colors.accentDim,
      borderWidth: 1,
      borderColor: colors.accent,
    },
    typeChipText: { fontSize: 14, color: colors.textMuted },
    typeChipTextActive: { color: colors.accent, fontWeight: "600" },
    prioritySection: { marginBottom: 4 },
    priorityLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.textMuted,
      marginBottom: 8,
    },
    priorityRow: { flexDirection: "row", gap: 8 },
    priorityBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingVertical: 10,
      borderRadius: 14,
      backgroundColor: colors.surfaceHover,
    },
    priorityDot: { width: 8, height: 8, borderRadius: 4 },
    priorityBtnText: {
      fontSize: 13,
      fontWeight: "500",
      color: colors.text,
    },
    categorySection: { marginBottom: 4 },
    categoryRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    categoryChip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 24,
      backgroundColor: colors.surfaceHover,
    },
    categoryChipActive: {
      backgroundColor: colors.accentDim,
      borderWidth: 1,
      borderColor: colors.accent,
    },
    categoryChipText: {
      fontSize: 14,
      color: colors.textMuted,
      flexShrink: 1,
    },
    categoryChipTextActive: { color: colors.accent, fontWeight: "600" },
    input: {
      backgroundColor: colors.surfaceHover,
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 14,
      fontSize: 16,
      color: colors.text,
    },
    reminderHint: {
      fontSize: 13,
      color: colors.textMuted,
      marginBottom: 8,
    },
    reminderPreview: { fontSize: 13, color: colors.accent, marginTop: 4 },
    pickerRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      padding: 14,
      backgroundColor: colors.surfaceHover,
      borderRadius: 16,
      marginBottom: 10,
    },
    pickerLabel: {
      fontSize: 15,
      fontWeight: "500",
      color: colors.text,
      minWidth: 80,
    },
    pickerValue: { flex: 1, fontSize: 15, color: colors.textMuted },
    dailyTimesRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 8,
    },
    timeChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 24,
      backgroundColor: colors.surfaceHover,
    },
    timeChipText: { fontSize: 14, color: colors.text, fontWeight: "500" },
    addTimeBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.accent,
      borderStyle: "dashed",
    },
    addTimeText: { fontSize: 14, color: colors.accent, fontWeight: "500" },
    requiredHint: { fontSize: 12, color: colors.danger, marginTop: -4 },
    checklistInputRow: { flexDirection: "row", gap: 8, marginBottom: 12 },
    checklistInput: {
      flex: 1,
      marginBottom: 0,
      backgroundColor: colors.surfaceHover,
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 14,
      fontSize: 16,
      color: colors.text,
    },
    addChecklistBtn: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: colors.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    checklistItemRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 10,
      paddingHorizontal: 12,
      backgroundColor: colors.surfaceHover,
      borderRadius: 14,
      marginBottom: 8,
    },
    checklistItemText: { fontSize: 15, color: colors.text, flex: 1 },
    removeItemBtn: { padding: 4 },
    recurrenceTypeRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 12,
    },
    recurrenceChip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 24,
      backgroundColor: colors.surfaceHover,
    },
    recurrenceChipText: { fontSize: 14, color: colors.textMuted },
    weekdaysRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 12,
    },
    weekdayChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 24,
      backgroundColor: colors.surfaceHover,
    },
    weekdayChipActive: {
      backgroundColor: colors.accentDim,
      borderWidth: 1,
      borderColor: colors.accent,
    },
    weekdayChipText: { fontSize: 14, color: colors.textMuted },
    weekdayChipTextActive: { color: colors.accent, fontWeight: "600" },
    dayOfMonthRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 12,
    },
    dayOfMonthChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 24,
      backgroundColor: colors.surfaceHover,
    },
    monthsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 12,
    },
    monthChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 24,
      backgroundColor: colors.surfaceHover,
    },
    monthChipText: { fontSize: 13, color: colors.textMuted },
    actions: {
      flexDirection: "row",
      gap: 12,
      justifyContent: "flex-end",
      flexWrap: "wrap",
      marginTop: 8,
    },
    primaryBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 14,
      paddingHorizontal: 24,
      borderRadius: 16,
      backgroundColor: colors.accent,
      flexShrink: 0,
    },
    primaryBtnDisabled: { opacity: 0.5 },
    primaryBtnText: { fontSize: 16, fontWeight: "600", color: colors.bg },
    secondaryBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 16,
      backgroundColor: colors.surfaceHover,
      flexShrink: 0,
      minWidth: 72,
    },
    secondaryBtnText: {
      fontSize: 16,
      fontWeight: "500",
      color: colors.text,
    },
    cancelBtn: {
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 16,
      flexShrink: 0,
      minWidth: 72,
      alignItems: "center",
      justifyContent: "center",
    },
    cancelBtnText: { fontSize: 16, color: colors.textMuted },
    saveBtn: {
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 16,
      backgroundColor: colors.accent,
      flexShrink: 0,
      minWidth: 88,
      alignItems: "center",
      justifyContent: "center",
    },
    saveBtnDisabled: { opacity: 0.5 },
    saveBtnText: { fontSize: 16, fontWeight: "600", color: colors.bg },
    pressed: { opacity: 0.8 },
  });
}
